#pragma once

//define all default parameters here. We must ensure that Tahoe and FireRender use the same.

//context
#define TAHOE_CONTEXT_DEFAULT_AA_CELL_SIZE 1U
#define TAHOE_CONTEXT_DEFAULT_AA_SAMPLES 1U
#define TAHOE_CONTEXT_DEFAULT_IMAGE_FILTER_TYPE 0
#define TAHOE_CONTEXT_DEFAULT_IMAGE_FILTER_BOX_RADIUS 1.0f
#define TAHOE_CONTEXT_DEFAULT_IMAGE_FILTER_GAUSSIAN_RADIUS 2.0f
#define TAHOE_CONTEXT_DEFAULT_IMAGE_FILTER_TRIANGLE_RADIUS 1.5f
#define TAHOE_CONTEXT_DEFAULT_IMAGE_FILTER_MITCHELL_RADIUS 2.0f
#define TAHOE_CONTEXT_DEFAULT_IMAGE_FILTER_LANCZOS_RADIUS 2.0f
#define TAHOE_CONTEXT_DEFAULT_IMAGE_FILTER_BLACKMANHARRIS_RADIUS 2.0f
#define TAHOE_CONTEXT_DEFAULT_TONE_MAPPING_TYPE 0

#define TAHOE_CONTEXT_DEFAULT_TONE_MAPPING_LINEAR_SCALE 1.0f

#define TAHOE_CONTEXT_DEFAULT_TONE_MAPPING_PHOTO_LINEAR_SENSITIVITY 100.f
#define TAHOE_CONTEXT_DEFAULT_TONE_MAPPING_PHOTO_LINEAR_EXPOSURE 1.f / 1000.f
#define TAHOE_CONTEXT_DEFAULT_TONE_MAPPING_PHOTO_LINEAR_FSTOP 2.8f

#define TAHOE_CONTEXT_DEFAULT_TONE_MAPPING_REINHARD02_PRE_SCALE 1.f
#define TAHOE_CONTEXT_DEFAULT_TONE_MAPPING_REINHARD02_POST_SCALE 1.2f
#define TAHOE_CONTEXT_DEFAULT_TONE_MAPPING_REINHARD02_BURN 3.75f

#define TAHOE_CONTEXT_DEFAULT_TONE_MAPPING_EXPONENTIAL_INTENSITY 1.0f
#define TAHOE_CONTEXT_DEFAULT_TONE_MAPPING_EXPONENTIAL_EXPOSURE 0.0f

#define TAHOE_CONTEXT_DEFAULT_MAX_RECURSION 2
#define TAHOE_CONTEXT_DEFAULT_RAY_CAST_EPISLON 0.0001f
#define TAHOE_CONTEXT_DEFAULT_AO_RAY_LENGTH 5.0f
#define TAHOE_CONTEXT_DEFAULT_RADIANCE_CLAMP FLT_MAX
#define TAHOE_CONTEXT_DEFAULT_X_FLIP 0U
#define TAHOE_CONTEXT_DEFAULT_Y_FLIP 1U
#define TAHOE_CONTEXT_DEFAULT_PREVIEW 0
#define TAHOE_CONTEXT_DEFAULT_FRAMECOUNT (-1)
#define TAHOE_CONTEXT_DEFAULT_OOC_TEXTURE_CACHE 0
#define TAHOE_CONTEXT_DEFAULT_TEXTURE_GAMMA 1.0f
#define TAHOE_CONTEXT_DEFAULT_DISPLAY_GAMMA 1.0f
#define TAHOE_CONTEXT_DEFAULT_CLIPPING_PLANE  0.0f ,0.0f ,0.0f ,0.0f   
#define TAHOE_CONTEXT_DEFAULT_PDF_THRESHOLD 0.005f
#define TAHOE_CONTEXT_DEFAULT_RENDER_STAGE 0x0000ffff
#define TAHOE_CONTEXT_DEFAULT_ROUGHNESS_CAP 0.0f
#define TAHOE_CONTEXT_DEFAULT_STACK_SIZE 64
#define TAHOE_CONTEXT_DEFAULT_TILESIZE 2048
#define TAHOE_CONTEXT_DEFAULT_MAXDIFFUSEDEPTH 0xffff
#define TAHOE_CONTEXT_DEFAULT_MAXGLOSSYDEPTH 0xffff
#define TAHOE_CONTEXT_DEFAULT_MAXREFRACTIONDEPTH 0xfff
#define TAHOE_CONTEXT_DEFAULT_MAXGLOSSYREFRACTIONDEPTH 0xffff
#define TAHOE_CONTEXT_DEFAULT_TRANSPARENTBACKGROUND false
#define TAHOE_CONTEXT_DEFAULT_MAXSHADOWDEPTH 2

//camera
#define TAHOE_CAMERA_DEFAULT_IPD 0.063f
#define TAHOE_CAMERA_DEFAULT_POSITION 0.f,0.f,3.5f
#define TAHOE_CAMERA_DEFAULT_LOOKAT 0.0f, 0.0f, -1.0f 
#define TAHOE_CAMERA_DEFAULT_UP  0.f,1.f,0.f
#define TAHOE_CAMERA_DEFAULT_NEAR_PLANE 0.01f
#define TAHOE_CAMERA_DEFAULT_FAR_PLANE 10000.0f

//shape
#define TAHOE_SHAPE_DEFAULT_SUBDIVISION_FACTOR 0
#define TAHOE_SHAPE_DEFAULT_DISPLACEMENT_SCALE_MIN 0.0f
#define TAHOE_SHAPE_DEFAULT_DISPLACEMENT_SCALE_MAX 1.0f
#define TAHOE_SHAPE_DEFAULT_UVDIM 2

//post effect
#define TAHOE_POSTEFFECT_DEFAULT_WHITE_BALANCE_COLOR_TEMPERATURE 6500.0f
#define TAHOE_POSTEFFECT_DEFAULT_SIMPLE_TONEMAP_EXPOSURE 0.0f 
#define TAHOE_POSTEFFECT_DEFAULT_SIMPLE_TONEMAP_CONTRAST 1.0f 

//light
#define TAHOE_DIRECTIONNALLIGHT_DEFAULT_ANGLE (0.5f/180.f*(float)M_PI)    // in radian, [ 0  ;  pi ]
#define TAHOE_SKYLIGHT_DEFAULT_DIRECTION 0.0f , 1.0f , 0.0f


//image
#define TAHOE_IMAGE_DEFAULT_IMAGE_GAMMA -1.0f 
#define TAHOE_IMAGE_DEFAULT_IMAGE_MIPMAPENABLED false

// ... todo : all types of nodes ...




